// Code generated by nvidia_versions_gen.go; DO NOT EDIT.

package misc

// GetNvidiaVersions returns the latest NVIDIA driver version per release branch
// Generated from https://docs.nvidia.com/datacenter/tesla/drivers/releases.json
// Only includes versions released in 2024 or later
// Keeps up to 2 minor versions for each major version
func GetNvidiaVersions() []string {
	return []string{
		"570.86.15",
		"570.124.06",
		"565.57.01",
		"560.35.03",
		"550.144.03",
		"550.127.08",
		"535.230.02",
		"535.216.03",
		"470.256.02",
		"470.239.06",
	}
}

const KubernetesVersion = "v1.32.1"
const NvidiaRuntimeVersion = "v1.16.2"
const GpuOperatorVersion = "v24.9.2"
